project:
  type: website
  output-dir: docs

# Metadata defaults for all documents
author:
  - name: Caspar David Peter
    orcid: 0000-0003-0020-1673
    email: peter@rsm.nl
    affiliations: "Rotterdam School of Management, Accounting Department"

bibliography: ["References/references.bib"]
csl: References/journal-of-financial-economics.csl

website:
  title: "Advanced Research Methods"
  site-url: https://CasparDP/bsc-arm
  navbar:
    background: "#0c1019"
    foreground: "#ff9e45"
    left:
      - text: "Lecture Slides"
        href: Advance research methods.html
      - text: "Lecture Notes"
        href: lecture_notes.html

format:
  html:
    theme: theme/custom.scss
    css: theme/rsm.css
    toc: false
    embed-resources: true
  revealjs:
    theme: theme/custom.scss
    logo: "Pics/Rotterdam_School_of_Management,_Erasmus_University_Rotterdam_(RSM)_Logo.png"
    footer: "Advanced research methods"
    code-tools: true
    code-overflow: wrap
    auto-stretch: true
    smaller: false
    transition: "slide"
    slideNumber: true
    embed-resources: true
    echo: true
    callout-appearance: simple
    code-fold: false
    citations-hover: true
    fig-width: 7
    fig-height: 4
    mermaid-format: png
    menu: false
    slide-level: 2
    highlight-style: dracula
